import React from 'react';
import Head from 'next/head'
import Navbar from './Navbar';
import styles from '../styles/Home.module.css'

const Header = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  );
}

export default Header;
