import Head from 'next/head'
import { initializeApp } from "firebase/app" // firebase SDK
import "firebase/firestore";  // firebase database
import { getAuth } from "firebase/auth";  // firebase database
import { useAuthState } from "react-firebase-hooks/auth";
import SignIn from "../components/SignIn";
import ChatRoom from '../components/ChatRoom';
import styles from '../styles/Home.module.css'

const app = initializeApp({
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_MEASUREMENT_ID
})
const auth = getAuth(app)

export default function Home() {
  const [user, loading, error] = useAuthState(auth)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">gitRa</a>
        </h1>
        <section>
          {user ? <ChatRoom auth={auth} app={app} /> : <SignIn auth={auth} />}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            gitRa
          </span>
        </a>
      </footer>
    </div>
  )
}